### ISSUE TITLE
can't build, pod install issue

### ISSUE THREAD

**Issue by CaledoniaProject** [google/santa#64]
I'm unable to install due to missing pods,

```
%> pod install
Analyzing dependencies
[!] The version of CocoaPods used to generate the lockfile (1.0.1) is higher than the version of the current executable (1.0.0). Incompatibility issues may arise.
[!] Unable to find a specification for `MOLAuthenticatingURLSession
```

Any ideas?

**Comment by arubdesu** [comment]
Did you pull from a (pre)release tag?

**Comment by CaledoniaProject** [comment]
Nope, it's the master branch

**Comment by CaledoniaProject** [comment]
Just tried 0.9.2 tag, still the same error.

**Comment by arubdesu** [comment]
What OS are you building on? I don't have much else to assist with for now, but specs would help for reproducing

**Comment by russellhancox** [comment]
Try 'pod repo update' to update the specs repo locally. pod install used to
do this automatically but stopped when they released 1.0

**Comment by tburgin** [comment]
Looks like you just need to update your cocoa pod install to version 1.0.1.
https://guides.cocoapods.org/using/getting-started.html

**Comment by CaledoniaProject** [comment]
Confirmed, `pod repo update` works for me, however it still fails 

```
%> rake build:release
xcpretty is not installed. Install with 'sudo gem install xcpretty'
Building with configuration: Release
User defaults from command line:
    IDEDerivedDataPathOverride = /tmp/santa-0.9.12/Build

=== BUILD TARGET LogicTests OF PROJECT Santa WITH CONFIGURATION Release ===

Check dependencies
The file “Pods-LogicTests.release.xcconfig” couldn’t be opened because there is no such file. (/tmp/santa-0.9.12/Pods/Target Support Files/Pods-LogicTests/Pods-LogicTests.release.xcconfig)

Write auxiliary files
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/Santa.build/Release/LogicTests.build/LogicTests-project-headers.hmap
/bin/mkdir -p /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/Tests-Prefix-bhosyyiahurvccdtjecbtsgtqtdq
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/Tests-Prefix-bhosyyiahurvccdtjecbtsgtqtdq/Tests-Prefix.pch.pch.hash-criteria
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/Santa.build/Release/LogicTests.build/LogicTests.hmap
/bin/mkdir -p /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/Tests-Prefix-gbhhcyuhbtkmnharrngoffgmapkn
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/Tests-Prefix-gbhhcyuhbtkmnharrngoffgmapkn/Tests-Prefix.pch.pch.hash-criteria
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/Santa.build/Release/LogicTests.build/Objects-normal/x86_64/LogicTests.LinkFileList
/bin/mkdir -p /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/Tests-Prefix-geaeqilseafkmwbqkyagesozjtdt
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/Tests-Prefix-geaeqilseafkmwbqkyagesozjtdt/Tests-Prefix.pch.pch.hash-criteria
/bin/mkdir -p /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/Tests-Prefix-einkrhgmokagkigvdqulpacetnst
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/Tests-Prefix-einkrhgmokagkigvdqulpacetnst/Tests-Prefix.pch.pch.hash-criteria

=== BUILD TARGET santactl OF PROJECT Santa WITH CONFIGURATION Release ===

Check dependencies
The file "Pods-santactl.release.xcconfig" couldn’t be opened because its path couldn't be resolved.  It may be missing.

Write auxiliary files
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/Santa.build/Release/santactl.build/santactl.hmap
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/Santa.build/Release/santactl.build/santactl-project-headers.hmap
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/Santa.build/Release/santactl.build/Objects-normal/x86_64/santactl.LinkFileList
/bin/mkdir -p /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/santactl-Prefix-ewcrdifxunlgytctccticgewyjuo
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/santactl-Prefix-ewcrdifxunlgytctccticgewyjuo/santactl-Prefix.pch.pch.hash-criteria
/bin/mkdir -p /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/santactl-Prefix-clvsmdfmfoqicvcoutvrhadribsb
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/santactl-Prefix-clvsmdfmfoqicvcoutvrhadribsb/santactl-Prefix.pch.pch.hash-criteria

=== BUILD TARGET santad OF PROJECT Santa WITH CONFIGURATION Release ===

Check dependencies
The file "Pods-santad.release.xcconfig" couldn’t be opened because its path couldn't be resolved.  It may be missing.

Write auxiliary files
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/Santa.build/Release/santad.build/Objects-normal/x86_64/santad.LinkFileList
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/Santa.build/Release/santad.build/santad-project-headers.hmap
/bin/mkdir -p /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/santad-Prefix-deljgcykkayedsgegkzhcduqddkk
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/santad-Prefix-deljgcykkayedsgegkzhcduqddkk/santad-Prefix.pch.pch.hash-criteria
/bin/mkdir -p /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/santad-Prefix-evxvmnbfitsvlygkbcjyehpicqma
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/santad-Prefix-evxvmnbfitsvlygkbcjyehpicqma/santad-Prefix.pch.pch.hash-criteria
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/Santa.build/Release/santad.build/santad.hmap

=== BUILD TARGET Santa OF PROJECT Santa WITH CONFIGURATION Release ===

Check dependencies
The file “Pods-Santa.release.xcconfig” couldn’t be opened because there is no such file. (/tmp/santa-0.9.12/Pods/Target Support Files/Pods-Santa/Pods-Santa.release.xcconfig)

Write auxiliary files
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/Santa.build/Release/Santa.build/Santa-project-headers.hmap
/bin/mkdir -p /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/Santa-Prefix-emilbfdvlieaundntiaazestsdsf
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/Santa-Prefix-emilbfdvlieaundntiaazestsdsf/Santa-Prefix.pch.pch.hash-criteria
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/Santa.build/Release/Santa.build/Objects-normal/x86_64/Santa.LinkFileList
/bin/mkdir -p /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/Santa-Prefix-efvovkknupgrkvbxrziiasfoihsb
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/PrecompiledHeaders/Santa-Prefix-efvovkknupgrkvbxrziiasfoihsb/Santa-Prefix.pch.pch.hash-criteria
write-file /tmp/santa-0.9.12/Build/Build/Intermediates/Santa.build/Release/Santa.build/Santa.hmap

PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock Build/Build/Intermediates/Santa.build/Release/Santa.build/Script-373591F801D7B22635DAD7A0.sh
    cd /tmp/santa-0.9.12
    /bin/sh -c /tmp/santa-0.9.12/Build/Build/Intermediates/Santa.build/Release/Santa.build/Script-373591F801D7B22635DAD7A0.sh
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock Build/Build/Intermediates/Santa.build/Release/Santa.build/Script-373591F801D7B22635DAD7A0.sh
(1 failure)
rake aborted!
Fail
/private/tmp/santa-0.9.12/Rakefile:23:in `xcodebuild'
/private/tmp/santa-0.9.12/Rakefile:75:in `block (2 levels) in <top (required)>'
/private/tmp/santa-0.9.12/Rakefile:69:in `block (2 levels) in <top (required)>'
Tasks: TOP => build:build
(See full trace by running task with --trace)
```

**Comment by CaledoniaProject** [comment]
Just one question, should I try the master branch or 0.9.2 tag?

**Comment by russellhancox** [comment]
0.9.2 is pretty old, you could either use 0.9.12 (the latest stable) or master.

**Comment by russellhancox** [comment]
Hi CaledoniaProject, did you get this sorted?

**Comment by CaledoniaProject** [comment]
I'm receiving the following error with master branch,

```
%> rake build:release --trace
** Invoke build:release (first_time)
** Execute build:release
** Invoke build:build (first_time)
** Invoke init (first_time)
** Execute init
** Execute build:build
Building with configuration: Release
▸ Building Pods/MOLCertificate [Release]
▸ Check Dependencies
▸ Building Santa/KernelTests [Release]
▸ Check Dependencies
▸ Building Pods/OCMock [Release]
▸ Check Dependencies
▸ Building Pods/FMDB [Release]
▸ Check Dependencies
▸ Building Pods/MOLCodesignChecker [Release]
▸ Check Dependencies
▸ Building Pods/MOLAuthenticatingURLSession [Release]
▸ Check Dependencies
▸ Building Pods/Pods-santad [Release]
▸ Check Dependencies
▸ Building Pods/Pods-santactl [Release]
▸ Check Dependencies
▸ Building Santa/santad [Release]
▸ Check Dependencies
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Running script '[CP] Copy Pods Resources'
▸ Building Santa/santactl [Release]
▸ Check Dependencies
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Running script '[CP] Copy Pods Resources'
▸ Building Pods/Pods-Santa [Release]
▸ Check Dependencies
▸ Building Santa/Santa [Release]
▸ Check Dependencies
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Running script '[CP] Embed Pods Frameworks'
▸ Running script '[CP] Copy Pods Resources'
▸ Building Pods/Pods-LogicTests [Release]
▸ Check Dependencies
▸ Building Santa/LogicTests [Release]
▸ Check Dependencies
▸ Building Santa/santa-driver [Release]
▸ Check Dependencies
▸ Running script 'Update Module Version'
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Update\ Module\ Version Build/Build/Intermediates/Santa.build/Release/santa-driver.build/Script-0DD98E691A5DD5C900A754C6.sh
(1 failure)
rake aborted!
Fail
/private/tmp/santa-master/Rakefile:23:in `xcodebuild'
/private/tmp/santa-master/Rakefile:76:in `block (2 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/private/tmp/santa-master/Rakefile:70:in `block (2 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/bin/rake:37:in `<main>'
Tasks: TOP => build:build
```

**Comment by tburgin** [comment]
We can bypass rake and use xcodebuild to try and get some more information on your build error.
Let's start clean:
```sh
git clone https://github.com/google/santa.git
cd santa
pod install
xcodebuild -workspace Santa.xcworkspace -scheme All -configuration Release
```
What are your errors if any?

Just to clarify, are you looking to build so you can run santa? If so, we have pre-compiled signed binaries. https://github.com/google/santa/releases

**Comment by CaledoniaProject** [comment]
Oh I think I know the problem. It should be related to kernel signing.
