### ISSUE TITLE
Build fails on latest main for Apple M1 `Expected action_config for 'objc++-compile' to be configured`

### ISSUE THREAD

**Issue by ScottifyShopson** [google/santa#735]
I get a failed build when running `bazel build //Source/santa_driver` on current main (ad8aafbd07b76406e75fad913b634fa6b3cffe96):

```sh
➜  santa git:(main) bazel build //Source/santa_driver
ERROR: /private/var/tmp/_bazel_newson/56b2aa8eaf8cf3df53b3feed9448d4f4/external/bazel_tools/tools/objc/BUILD:35:13: in objc_library rule @bazel_tools//tools/objc:dummy_lib: Expected action_config for 'objc++-compile' to be configured
ERROR: /private/var/tmp/_bazel_newson/56b2aa8eaf8cf3df53b3feed9448d4f4/external/bazel_tools/tools/objc/BUILD:35:13: in objc_library rule @bazel_tools//tools/objc:dummy_lib: 
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/objc/objc_library.bzl", line 127, column 124, in _objc_library_impl
	File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 316, column 50, in _register_compile_and_archive_actions
	File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 394, column 66, in _cc_compile_and_link
	File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 193, column 29, in _compile
Error in compile: Expected action_config for 'objc++-compile' to be configured
ERROR: /private/var/tmp/_bazel_newson/56b2aa8eaf8cf3df53b3feed9448d4f4/external/bazel_tools/tools/objc/BUILD:35:13: Analysis of target '@bazel_tools//tools/objc:dummy_lib' failed
ERROR: Analysis of target '//Source/santa_driver:santa_driver' failed; build aborted: 
INFO: Elapsed time: 0.762s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (60 packages loaded, 620 targets configured)
```

I get a different error (https://github.com/google/santa/issues/489) when building on an Intel Mac, or when trying to build the tag version 2021.8 on my M1 and my Intel. 

Here's some system information:
```sh
➜  santa git:(82b71c0) xcode-select --print-path
/Library/Developer/CommandLineTools
➜  santa git:(82b71c0) bazel info release
release 5.0.0-homebrew
➜  santa git:(82b71c0) sw_vers
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
➜  santa git:(82b71c0) sysctl -n machdep.cpu.brand_string
Apple M1 Pro
```

**Comment by pmarkowsky** [comment]
The line `Expected action_config for 'objc++-compile' to be configured` looks like a [bazel crosstool issue](https://groups.google.com/g/bazel-discuss/c/IUljWK1umlQ).  So this could be related to how you've installed bazel.

Have you tried building with bazel's official release vs. bazel from homebrew? If so are you getting the same issue?

I know @tnek has been doing M1 builds and  I can confirm on my x64 mac that main is building.

**Comment by russellhancox** [comment]
Try installing Xcode and setting the devtools path to it, I'm not sure if the command-line tools contain enough of the necessary items to build. Once done, run `bazel purge` inside the santa project dir and try building again.

**Comment by ScottifyShopson** [comment]
I have installed Xcode and set the path to it. I also used the recommended `bazelisk` tool via homebrew as suggested here: https://bazel.build/install. I also see that 5.0.0 is the latest official release: https://github.com/bazelbuild/bazel/releases

Now my system looks like: 
```sh
➜  santa git:(main) xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
➜  santa git:(main) bazel info release
release 5.0.0
➜  santa git:(main) sw_vers
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
➜  santa git:(main) sysctl -n machdep.cpu.brand_string
Apple M1 Pro
```

And I get a new error when trying to build:
```sh
➜  santa git:(main) bazel clean --expunge
INFO: Starting clean.
➜  santa git:(main) bazel build //Source/santa_driver
Starting local Bazel server and connecting to it...
DEBUG: Rule 'build_bazel_rules_apple' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1644466310 -0800"
DEBUG: Repository build_bazel_rules_apple instantiated at:
  /Users/newson/src/github.com/google/santa/WORKSPACE:9:15: in <toplevel>
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_newson/56b2aa8eaf8cf3df53b3feed9448d4f4/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
DEBUG: Rule 'hedron_compile_commands' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1640416382 -0800"
DEBUG: Repository hedron_compile_commands instantiated at:
  /Users/newson/src/github.com/google/santa/WORKSPACE:26:15: in <toplevel>
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_newson/56b2aa8eaf8cf3df53b3feed9448d4f4/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed target //Source/santa_driver:santa_driver (60 packages loaded, 918 targets configured).
INFO: Found 1 target...
ERROR: /Users/newson/src/github.com/google/santa/Source/santa_driver/BUILD:43:23: Linking Source/santa_driver/santa_driver_bin failed: (Aborted): wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang @bazel-out/macos-arm64-min10.9-applebin_macos-darwin_arm64-fastbuild-ST-45c51dd51b5d/bin/Source/santa_driver/santa_driver_bin-2.params

Use --sandbox_debug to see verbose messages from the sandbox
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
Target //Source/santa_driver:santa_driver failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 16.174s, Critical Path: 1.25s
INFO: 37 processes: 28 internal, 9 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by russellhancox** [comment]
I'd completely missed that you're trying to build the driver. bazel defaults to your running arch for building, which is fine generally but kexts can only be built on x86_64 so you have to _guide_ bazel to do the right thing:

```
rah@rah-m1mini ~/src/santa [main=]                                                                           
» bazel build //Source/santa_driver
INFO: Analyzed target //Source/santa_driver:santa_driver (0 packages loaded, 801 targets configured).
INFO: Found 1 target...
ERROR: /Users/rah/src/santa/Source/santa_driver/BUILD:43:23: Linking Source/santa_driver/santa_driver_bin failed: (Aborted): wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang @bazel-out/macos-arm64-min10.9-applebin_macos-darwin_arm64-fastbuild-ST-c77b4cf2f187/bin/Source/santa_driver/santa_driver_bin-2.params

Use --sandbox_debug to see verbose messages from the sandbox
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
Target //Source/santa_driver:santa_driver failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.454s, Critical Path: 0.14s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully
```

vs

```
rah@rah-m1mini ~/src/santa [main=]
» bazel build //Source/santa_driver --macos_cpus x86_64
INFO: Build option --macos_cpus has changed, discarding analysis cache.
INFO: Analyzed target //Source/santa_driver:santa_driver (0 packages loaded, 801 targets configured).
INFO: Found 1 target...
INFO: From Linking Source/santa_driver/santa_driver_bin:
ld: warning: object file (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/lib/libkmod.a(c_start.o)) was built for newer macOS version (12.0) than being linked (10.9)
ld: warning: object file (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/lib/libkmod.a(c_stop.o)) was built for newer macOS version (12.0) than being linked (10.9)
warning: no debug symbols in executable (-arch x86_64)
Target //Source/santa_driver:santa_driver up-to-date:
  bazel-out/applebin_macos-darwin_x86_64-fastbuild-ST-cb634f43adf0/bin/Source/santa_driver/santa_driver.zip
  bazel-out/applebin_macos-darwin_x86_64-fastbuild-ST-cb634f43adf0/bin/Source/santa_driver/santa-driver.kext.dSYM/Contents/Resources/DWARF/santa-driver
  bazel-out/applebin_macos-darwin_x86_64-fastbuild-ST-cb634f43adf0/bin/Source/santa_driver/santa-driver.kext.dSYM/Contents/Info.plist
INFO: Elapsed time: 3.360s, Critical Path: 3.06s
INFO: 26 processes: 12 internal, 13 darwin-sandbox, 1 local.
INFO: Build completed successfully, 26 total actions
```

**Comment by ScottifyShopson** [comment]
Aha! ok, `bazel build //Source/santa_driver --macos_cpus x86_64` succeeded for me. 

What's the 'build everything' target? I was just following the docs for building here: https://github.com/google/santa/blob/main/docs/development/building.md

**Comment by russellhancox** [comment]
Good question (our docs need updating). It depends on what you want to do; for local testing you can do `bazel run //:reload` to build (sans kernel driver) and load locally, though this will require provisioning profiles or SIP disabled. You can build a full release using `bazel build //:release -c opt --macos_cpus x86-64,arm64` to get everything built and packaged up. And if you just want to build the app bundle to make sure everything but the driver builds you can do `bazel build //Source/santa`, which builds the .app with the system extension embedded.

Building the driver at this point is largely not important as it will be removed in the next release.

**Comment by ScottifyShopson** [comment]
Ok, `bazel build //:release -c opt --macos_cpus arm64` and `bazel build //Source/santa:Santa` and `bazel run //:reload` work fairly well, though I don't have a provisioning profile set up so they fail with: 
```
ERROR: /Users/newson/src/github.com/google/santa/Source/santad/BUILD:128:13: Creating symlink bazel-out/applebin_macos-darwin_arm64-fastbuild-ST-45c51dd51b5d/bin/Source/santad/com.google.santa.daemon-intermediates/embedded.provisionprofile failed: missing input file '//Source/santad:Santa_Daemon_Dev.provisionprofile'
```

What's a 'provisioning profile'? Is the first line [here](https://help.apple.com/xcode/mac/current/#/deva899b4fe5) the same 'provisioning profile'? I'm completely new to macOS/objectiveC development, but could ask around in my team if this is something standard for macOS/iOS development.

**Comment by russellhancox** [comment]
That Apple link does describe provisioning profiles and it is one of those profiles that's needed to sign Santa in a way that will allow it to be loaded as a system extension. Santa currently requires 2 profiles:

1. A "Daemon" provisioning profile used to sign santad. This profile requires the `com.apple.developer.endpoint-security.client` entitlement
2. An "App" provisioning profile used to sign Santa.app. This profile requires the `com.apple.developer.system-extension.install` entitlement.

If acquiring profiles with these entitlements is infeasible, the alternative is to disable SIP on your machine and add the `--define=SANTA_BUILD_TYPE=ci` flag to your bazel invocations (which will not try to use provisioning profiles during signing)

**Comment by ScottifyShopson** [comment]
Thanks!
